CREATE OR REPLACE TABLE theme_scores AS
SELECT
    SURVEYR,
    INDICATORID,
    INDICATORENG,
    SUBINDICATORID,
    SUBINDICATORENG,
    AVG(SCORE100) AS mean_score
FROM pses_analysis
WHERE QUESTION IN ({FSQ})
  AND QUESTION NOT LIKE 'Q73%'
GROUP BY
    SURVEYR,
    INDICATORID,
    INDICATORENG,
    SUBINDICATORID,
    SUBINDICATORENG
ORDER BY
    INDICATORID,
    SUBINDICATORID,
    SURVEYR